### ISSUE TITLE
Delete domain from custom list throws missing argument error

### ISSUE THREAD

**Issue by redelsoft** [ccmarris/python-bloxone#3]
Adding domains to custom lists with add_items_to_custom_list() works, but deleting throws an objpath error.
**add a domain:**
tdc = bloxone.b1tdc("bloxone.ini")
tdc.add_items_to_custom_list(name="Custom Block List", items=["test.xyz"])

**remove a domain:**
tdc = bloxone.b1tdc("bloxone.ini")
tdc.delete_items_from_custom_list(name="Custom Block List", items=["test.xyz"])
Traceback (most recent call last):
  File "\bloxonetd\editList.py", line 43, in <module>
    tdc.delete_items_from_custom_list(name="Custom Block List", items=["test.xyz"]).json()
  File "\Python\Python38\lib\site-packages\bloxone\b1tdc.py", line 397, in delete_items_from_custom_list
    response = b1tdc.delete(request, body=json.dumps(body))
TypeError: delete() missing 1 required positional argument: 'objpath'

**Comment by mragusa** [comment]
I am also encountering an error with this same function call

Traceback (most recent call last):
  File "/Users/*/b1ddi/./b1td-named-lists.py", line 183, in <module>
    main()
  File "/Users/*/b1ddi/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/b1ddi/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/*/b1ddi/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/b1ddi/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/b1ddi/./b1td-named-lists.py", line 78, in main
    response = b1tdc.delete_items_from_custom_list(name, items_described=[{"description": comment, "item": item}])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/*/b1ddi/venv/lib/python3.12/site-packages/bloxone/b1tdc.py", line 397, in delete_items_from_custom_list
    response = b1tdc.delete(request, body=json.dumps(body))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: b1tdc.delete() missing 1 required positional argument: 'objpath'

**Comment by mragusa** [comment]
Issue has been resolved with latest update.
